--insert into todo(id, username,description,target_date,is_done)
--values(10001, 'Sneha', 'Learn JPA', CURRENT_DATE(), false),
--      (10002, 'Preetam', 'Learn Data JPA', CURRENT_DATE(), false),
--      (10003, 'Pratiksha', 'Learn Microservices', CURRENT_DATE(), false),
--
--      (10004, 'Sneha', 'Learn programming', CURRENT_DATE(), false);